


# version: '3'
# services:
#   root-config:
#     build:
#       context: .
#       dockerfile: Dockerfile-root
#     ports:
#       - "9000:9000"

#   react-tasks:
#     build:
#       context: .
#       dockerfile: Dockerfile-react
#     ports:
#       - "3000:3000"
  


#   angular-login:
#     build:
#       context: .
#       dockerfile: Dockerfile-angular
#     ports:
#       - "4200:4200"

#   nginx:
#     build:
#       context: .
#       dockerfile: Dockerfile-nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - root-config
#       - react-tasks
    
#       - angular-login




# version: '3'
# services:
#   root-config:
#     build: ./root-config
#     ports:
#       - "9000:9000"
#     networks:
#       - microfrontend-network

#   angular-login:
#     build: ./angular-login
#     ports:
#       - "80:80"
#     networks:
#       - microfrontend-network

#   react-task:
#     build: ./react-tasks
#     ports:
#       - "3000:3000"
#     networks:
#       - microfrontend-network

#   create-users:
#     build: ./create-users
#     ports:
#       - "3001:3001"
#     networks:
#       - microfrontend-network

# networks:
#   microfrontend-network:
#     driver: bridge




version: '3'

services:
  root-config:
    build: ./root-config
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  angular-login:
    build: ./angular-login
    ports:
      - "4200:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  react-task:
    build: ./react-tasks
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  create-users:
    build: ./create-users
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    name: microfrontend-network