
# # # services:
# # #   root-config:
# # #     build:
# # #       dockerfile: Dockerfile-root
# # #     ports:
# # #       - "9000:9000"

# # #   react-tasks:
# # #     build:
# # #       dockerfile: Dockerfile-react
# # #     ports:
# # #       - "3000:3000"

# # #   angular-login:
# # #     build:
# # #       dockerfile: Dockerfile-angular
# # #     ports:
# # #       - "4200:8080"


# # version: '3'

# # services:
# #   root-config:
# #     build:
    
# #       dockerfile: Dockerfile-root
# #     ports:
# #       - "9000:9000"

# #   react-tasks:
# #     build:
    
# #       dockerfile: Dockerfile-react
# #     ports:
# #       - "3000:3000"

# #   angular-login:
# #     build:
     
# #       dockerfile: Dockerfile-angular
# #     ports:
# #       - "4200:4200"

# #   nginx:
# #     image: nginx:alpine
# #     volumes:
# #       - ./nginx.conf:/etc/nginx/nginx.conf
# #     ports:
# #       - "80:80"
# #     depends_on:
# #       - root-config
# #       - react-tasks
# #       - angular-login


# version: '3'
# services:
#   root-config:
#     build:
      
#       dockerfile: Dockerfile-root
#     ports:
#       - "9000:9000"

#   react-app:
#     build:
    
#       dockerfile: Dockerfile-react
#     ports:
#       - "3000:3000"

#   angular-app:
#     build:
     
#       dockerfile: Dockerfile-angular
#     ports:
#       - "4200:4200"

#   nginx:
#     build:
     
#       dockerfile: Dockerfile-nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - root-config
#       - react-app
#       - angular-app



# version: '3'
# services:
#   root-config:
#     build:
#       context: .
#       dockerfile: Dockerfile-root
#     ports:
#       - "9000:9000"

#   react-tasks:
#     build:
#       context: .
#       dockerfile: Dockerfile-react
#     ports:
#       - "3000:3000"
  
#   create-users:
#     build:
#       context: .
#       dockerfile: Dockerfile-vue
#     ports:
#       - "3001:3001"

#   angular-login:
#     build:
#       context: .
#       dockerfile: Dockerfile-angular
#     ports:
#       - "4200:4200"

#   nginx:
#     build:
#       context: .
#       dockerfile: Dockerfile-nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - root-config
#       - react-tasks
#       - create-users
#       - angular-login




version: '3'
services:
  angular-login:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

 