

# FROM nginx:alpine

# COPY /nginx.conf /etc/nginx/nginx.conf
# # COPY --from=build /Single-spa-app/create-users/dist /usr/share/nginx/html/create-users

# # # Copiar los archivos construidos de React
# # COPY --from=build /Single-spa-app/react-tasks/dist /usr/share/nginx/html/react-tasks

# # # Copiar los archivos construidos de Angular
# # COPY --from=build /Single-spa-app/angular-login/dist /usr/share/nginx/html/angular-login
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]