# Dockerfile-vue
FROM node:18 as build
WORKDIR /Single-spa-app
COPY create-users/package*.json ./create-users/
WORKDIR /Single-spa-app/create-users
RUN npm install

COPY . /Single-spa-app

WORKDIR /Single-spa-app/create-users
RUN npm run build

EXPOSE 3001
CMD ["npm", "run", "serve"]




