
version: '3'

services:
  root-config:
    build: ./root-config
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  angular-login:
    build: ./angular-login
    ports:
      - "4200:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  react-task:
    build: ./react-tasks
    ports:
      - "3000:3000"
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  create-users:
    build: ./create-users
    ports:
      - "3001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  default:
    name: microfrontend-network





# version: '3'

# services:
#   root-config:
#     build: ./root-config
#     ports:
#       - "9000:80"
#     volumes:
#       - ./root-config/nginx.conf:/etc/nginx/nginx.conf:ro

#   angular-login:
#     build: ./angular-login
#     ports:
#       - "4200:80"
#     volumes:
#       - ./angular-login/nginx.conf:/etc/nginx/nginx.conf:ro

#   react-tasks:
#     build: ./react-tasks
#     ports:
#       - "3000:80"
#     volumes:
#       - ./react-tasks/nginx.conf:/etc/nginx/nginx.conf:ro

#   create-users:
#     build: ./create-users
#     ports:
#       - "3001:80"
#     volumes:
#       - ./create-users/nginx.conf:/etc/nginx/nginx.conf:ro

# networks:
#   default:
#     name: microfrontend-network




