# # # Usar la imagen oficial de Node.js como imagen base
# # FROM node:18 AS build
# # RUN npm install -g @angular/cli
# # # Establecer el directorio de trabajo dentro del contenedor
# # WORKDIR /Single-spa-app/angular-login

# # # Copiar el package.json y el package-lock.json para instalar dependencias
# # COPY package*.json ./

# # # Instalar las dependencias del proyecto
# # RUN npm install


# # # Copiar el código fuente del proyecto al contenedor
# # COPY . .

# # # Construir la aplicación Angular para producción
# # RUN npm run build

# # # Usar una imagen ligera de Nginx para servir la aplicación Angular
# # FROM nginx:alpine
# # #COPY /nginx.conf /etc/nginx/conf.d/default.conf
# # # Copiar los archivos compilados de la etapa de construcción a la carpeta de Nginx
# # COPY --from=build /Single-spa-app/angular-login/dist/angular-login /usr/share/nginx/html

# # # Exponer el puerto 80 para el contenedor
# # EXPOSE 80

# # # Comando para ejecutar Nginx
# # CMD ["nginx", "-g", "daemon off;"]



# # # Etapa de construcción
# # FROM node:18 as build
# # WORKDIR /Single-spa-app/angular-login
# # COPY package*.json ./
# # RUN npm install
# # COPY . .
# # RUN npm run build

# # # Etapa de producción
# # FROM nginx:alpine
# # COPY --from=build /Single-spa-app/angular-login/dist/angular-login /usr/share/nginx/html
# # COPY nginx.conf /etc/nginx/nginx.conf
# # EXPOSE 80
# # CMD ["nginx", "-g", "daemon off;"]



# # Etapa de construcción
# FROM node:18 as build

# WORKDIR /Single-spa-app/angular-login

# # Copiar package.json y package-lock.json
# COPY package*.json ./

# # Instalar dependencias
# RUN npm install

# # Copiar el resto de los archivos de la aplicación
# COPY . .

# # Construir la aplicación para producción
# RUN npm run build -- --configuration production

# # Etapa de producción
# FROM nginx:alpine

# # Copiar los archivos de construcción desde la etapa anterior
# COPY --from=build /Single-spa-app/angular-login/dist/angular-login /usr/share/nginx/html

# # Copiar la configuración de Nginx
# COPY nginx.conf /etc/nginx/nginx.conf

# # Exponer el puerto 80
# EXPOSE 80

# # Iniciar Nginx
# CMD ["nginx", "-g", "daemon off;"]



# angular-login/Dockerfile
FROM node:18 as build
WORKDIR /Single-spa-app/angular-login
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production


FROM nginx:alpine
# Copiar los archivos de construcción desde la etapa anterior
COPY --from=build /Single-spa-app/angular-login/dist/angular-login /usr/share/nginx/html

# Copiar la configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
